# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MidAtlantic Dreamin‘
email: info@midatlanticdreamin.com
description: >- # this means to ignore newlines until "baseurl:"
  Mid-Atlantic Dreamin‘ is a community-led conference for professionals with
  a passion for the Salesforce platform. Join us May 8, 2023 at City Winery in Philadelphia.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://midatlanticdreamin.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@phillyforce"
github_username: jekyll
social_logo: img/logo.svg
metaKeywords: "event, salesforce, force.com, midatlantic dreaming, trailblazer, user conference"
googleAnalyticsTrackingId: "UA-154567667-1"

collections:
  questions:
    question: ""
    section: ""
    order: 0
    id: ""
  speakers:
    name: ""
    jobtitle: ""
    layout: "speaker"
    output: true
  sponsors:
    sponsor_name: ""
    url: ""
    logo: ""
    output: false
  sessions:
    speaker: ""
    layout: "session"
    output: true
collections_dir: collections

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
